# Generated by Django 3.1.3 on 2020-11-28 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
